# ============================================
# $Id: Makefile,v 1.1 2005/11/14 11:25:02 marc Exp $
# ============================================

appname = jscalendar
export appname

SUBDIR= lang
include $(utildir)/PubRule

DISTFILES +=  $(SUBDIR) $(wildcard *.html) $(wildcard *.txt)
