# ============================================
# $Id: Makefile,v 1.1 2007/07/06 12:56:34 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog.in changelog compat control copyright freedom-wgcal.dirs freedom-wgcal-osync.dirs freedom-wgcal-osync.postinst freedom-wgcal-osync.prerm freedom-wgcal.postinst rules wgcalosync

