# ============================================
# $Id: Makefile,v 1.2 2003/05/22 09:00:43 eric Exp $
# ============================================

SUBDIR= htmlarea
appname=$(applib)

include $(utildir)/PubRule

DISTFILES += $(SUBDIR) Makefile


$(pubdir)/htmlarea :
	cp -r htmlarea $(pubdir)



publish:$(pubdir)/htmlarea 
