#!/bin/bash
if [ "$dbpsql" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi

dbfreename=`$wpub/wsh.php --api=get_param --param=FREEDOM_DB | sed -e 's/^.*dbname[[:space:]]*=[[:space:]]*\([[:alnum:]]*\).*$/\1/'`
if [ "$dbfreename" = "" ]; then
    dbfreename="freedom";
fi
echo $dbname $dbfreename

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then

  echo "Create $dbfreename database"
  createdb --username=postgres --encoding LATIN1 $dbfreename
   if [ $? != 0 ] ; then
    echo "cannot create db $dbfreename"
    exit 1
  fi
   
  
  echo "ALTER DATABASE $dbfreename set DateStyle = sql,european;" | psql  --username=postgres $dbpsql
  psql $dbfree -f $wpub/WHAT/getprivilege.sql
  psql $dbfree -f $wpub/FDL/fdl.sql
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --appc=FDL --class=Doc
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --appc=FDL --class=DocRead
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --appc=FDL --class=DocPerm
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --appc=FDL --class=VGroup
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --appc=FDL --class=DocRel
  /usr/bin/php -q $wpub/API/updateclass.php --dbcoord="$dbfree" --class=Group
  #copy postgres group table
  $wpub/wsh.php --api=freedom_groups

  if [ -f /usr/share/pgsql/contrib/tsearch2.sql ]; then
    psql $dbfree -f /usr/share/pgsql/contrib/tsearch2.sql
  fi
  if [ -f /usr/share/postgresql/contrib/tsearch2.sql ]; then
    psql $dbfree -f /usr/share/postgresql/contrib/tsearch2.sql
  fi

  DBFREENAME=`echo $dbfreename | tr '[a-z]' '[A-Z]'`
  if [ ! -f $wpub/VAULT/$DBFREENAME.vault ]; then
    #cp $wpub/FDL/FREEDOM.vault $wpub/VAULT/FREEDOM.vault
    sed -e"s/fs1/$dbfreename/g" $wpub/FDL/FREEDOM.vault > $wpub/VAULT/$DBFREENAME.vault
  fi
  $wpub/wsh.php --api=vault_init

#  $wpub/wsh.php --app=FDL --action=FREEDOM_INIT  
 # psql $dbfreename anakeen -f $wpub/API/freedom_clean.sql
fi
#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then


  #copy postgres group table
  $wpub/wsh.php --api=freedom_groups


  $wpub/wsh.php --api=freedom_import --file=$wpub/FDL/fdl.ods
  $wpub/wsh.php --api=freedom_import --file=$wpub/FDL/freeaction.ods

  su - postgres -c "psql $dbfree -f $wpub/WHAT/getprivilege.sql"
  su - postgres -c "psql $dbfree -f $wpub/FDL/fdl.sql"
  $wpub/wsh.php --api=fdl_adoc
  $wpub/wsh.php --api=fdl_trigger | psql $dbfree
  $wpub/wsh.php --api=fdl_trigger --trigger=Y | psql $dbfree

fi
