# ============================================
# $Id: Makefile,v 1.3 2002/04/16 14:45:07 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Usercard Incident Generic


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
