# ============================================
# $Id: Makefile,v 1.6 2004/03/01 08:48:41 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Onefam Usercard  Generic 


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
