#!/bin/bash
if [ "$dbpsql" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi
#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then    
  createdb --username=postgres --encoding UTF8 webdav
  if [ $? != 0 ] ; then
    echo "cannot create db $dbfreename"
    exit 1
  fi
  psql webdav --username=postgres -f $wpub/DAV/dav-pg.sql
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
   echo
fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
