# ============================================
# $Id: Makefile,v 1.1 2004/11/29 08:44:27 marc Exp $
# ============================================

appname=$(applib)

DISTFILES += Makefile

$(pubdir)/freedom.src :
	cp freedom.src $(pubdir)

$(pubdir)/freedom.gif :
	cp freedom.gif $(pubdir)

$(pubdir)/freedomsearch.php :
	cp freedomsearch.php $(pubdir)

publish: $(pubdir)/freedom.src $(pubdir)/freedom.gif $(pubdir)/freedomsearch.php
