# ============================================
# $Id: Makefile,v 1.1 2007/11/27 15:55:30 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+= changelog changelog.in compat control copyright dirs postinst rules
