# ============================================
# $Id: Makefile,v 1.1 2007/06/29 11:50:25 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog.in changelog compat control copyright dirs docs postinst rules
