# ============================================
# $Id: Makefile,v 1.4 2003/01/24 14:10:46 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Fdl Freedom Usercard Incident


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
