# ============================================
# $Id: Makefile,v 1.1 2001/11/09 09:43:59 eric Exp $
# $Log: Makefile,v $
# Revision 1.1  2001/11/09 09:43:59  eric
# gestion documentaire
#
# Revision 1.1  2001/06/13 14:41:44  eric
# contact address book
#
# ============================================


include $(utildir)/PubRule
