# ============================================
# $Id: Makefile,v 1.1 2007/10/22 09:31:56 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
