# ============================================
# $Id: Makefile,v 1.1 2007/05/29 13:33:15 eric Exp $
# $Log: Makefile,v $
# Revision 1.1  2007/05/29 13:33:15  eric
# add command GET
#
#
# ============================================


include $(utildir)/PubRule
