# ============================================
# $Id: Makefile,v 1.1 2006/02/01 13:49:02 eric Exp $
# $Log: Makefile,v $
# Revision 1.1  2006/02/01 13:49:02  eric
# soap
#
# Revision 1.1  2002/09/02 16:45:09  eric
# mise en place tarif & catalogue
#
# Revision 1.1  2001/06/13 14:41:44  eric
# contact address book
#
# ============================================


include $(utildir)/PubRule
