# ============================================
# $Id: Makefile,v 1.3 2005/05/23 16:18:06 marc Exp $
# ============================================
include $(utildir)/PubRule
appname=osync
DISTFILES=  $(wildcard *.php) Makefile
