# ============================================
# $Id: Makefile,v 1.1 2005/04/11 19:06:30 marc Exp $
# ============================================
include $(utildir)/PubRule

DISTFILES=  $(wildcard *.php) Makefile
