# ============================================
# $Id: Makefile,v 1.2 2006/04/25 20:58:12 marc Exp $
# ============================================

include $(utildir)/PubRule

DISTFILES +=  wgcal.ico
$(pubdir)/$(appname)/wgcal.ico : wgcal.ico
	cp $< $(pubdir)/$(appname)/Images
publish: $(pubdir)/$(appname)/wgcal.ico 
