# ============================================
# $Id: Makefile,v 1.1 2008/03/13 10:09:23 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
