# ============================================
# $Id: Makefile,v 1.1 2006/11/03 15:53:45 eric Exp $
# ============================================


SUBDIR= mime
include $(utildir)/PubRule
DISTFILES += $(SUBDIR) Makefile

