# ============================================
# $Id: Makefile,v 1.8 2007/10/17 04:47:32 marc Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Fdl Freedom Onefam Generic Usercard  Fgsearch

include $(utildir)/PubRule

DISTFILES = $(SUBDIR) Makefile
