# ============================================
# $Id: Makefile,v 1.4 2002/04/17 09:03:12 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Fdl Freedom Usercard Incident Product Site Contract


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
