# ============================================
# $Id: Makefile,v 1.6 2002/08/28 09:39:33 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Fdl Freedom Onefam Generic Usercard Incident Product Site Contract


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
