# ============================================
# $Id: Makefile,v 1.5 2002/05/15 13:32:27 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Usercard Incident Generic Product


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
