# ============================================
# $Id: Makefile,v 1.2 2002/02/05 16:34:06 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
