# ============================================
# $Id: Makefile,v 1.8 2004/08/12 06:59:45 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Onefam Usercard  Generic  Fusers


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
