# ============================================
# $Id: Makefile,v 1.1 2007/10/22 13:30:11 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog.in changelog compat control copyright dirs docs postinst rules
