# ============================================
# $Id: Makefile,v 1.1 2007/07/10 12:25:46 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright rules freedom-te.dirs freedom-te-client.dirs 
