# ============================================
# $Id: Makefile,v 1.1 2006/11/08 17:47:44 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= $(wildcard [^Makefile]*)

include $(utildir)/PubRule


DISTFILES += $(SUBDIR) Makefile
