# ============================================
# $Id: Makefile,v 1.1 2008/08/04 09:49:02 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
