# ============================================
# $Id: Makefile,v 1.1 2002/03/01 09:36:42 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Usercard 


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
