# ============================================
# $Id: Makefile,v 1.2 2002/08/19 12:15:34 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Site Product Contract Incident Usercard 


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
