# ============================================
# $Id: Makefile,v 1.3 2004/08/24 13:36:37 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Freedom Site Product Contract Incident Usercard 


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
