#!/bin/bash

pubdir="/home/httpd/what";

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
    # add plug in footer
  $pubdir/wsh.php --app=APPMNG --action=PARAM_MOD --appid=1 --aname=CORE_PLUGZONE --atype=G --val=FREEDOM:SPEEDSEARCH

  
fi
#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
 ;


fi
