# ============================================
# $Id: Makefile,v 1.2 2005/11/14 11:33:22 marc Exp $
# ============================================

appname = jsXMLParser
export appname

SUBDIR= lang
include $(utildir)/PubRule

DISTFILES +=  $(SUBDIR) $(wildcard *.js)
