#!/bin/bash
#sed -e 's/<[^>]*>//g' $1 > $2

perl -e '$/=undef;$html=<>;$html=~s/<\!--.*?-->//gms;$html=~s/<script.*?<\/script>//igms;$html=~s/<style.*?<\/style>//igms;$html=~s/<[^>]*>//gms;print$html' $1 > $2
#perl -e 'use HTML::Entities;$/=undef;$html=<>;$html=~s/<\!--.*?-->//gms;$html=~s/<script.*?<\/script>//igms;$html=~s/<style.*?<\/style>//igms;$html=~s/<[^>]*>//gms;decode_entities($html);print($html)' $1 > $2

LANG=C recode -f HTML..l9 $2
