#!/bin/bash
#/usr/lib/openoffice.org2.0/program/unopkg add --shared OOo-FreeDom.uno.pkg
# Xfvb :0
# for apache : echo 0 > /proc/sys/kernel/exec-shield  
# Alternatively, you can add the following option to the /etc/sysctl.conf

TMPPATH=/var/tmp
ooffice -display :0  -norestore -invisible -headless -nologo -env:UserInstallation=file:///$TMPPATH/.OOo_$$  "macro:///FreeDom.FreeDom.exportPdf($1,$2)"
/bin/rm -r $TMPPATH/.OOo_$$
