#!/bin/bash
#/usr/lib/openoffice.org2.0/program/unopkg add --shared OOo-FreeDom.uno.pkg
UF=$2.t
ooffice -display :0  -norestore -invisible -headless -nologo -env:UserInstallation=\$SYSUSERCONFIG/.OOo_$$  "macro:///FreeDom.FreeDom.exportUTF8($1,$UF)"
if [ -f $UF ]; then
    iconv  -f utf-8 -t latin1//TRANSLIT $UF > $2
    /bin/rm $UF
else
    exit 1;
fi