#!/bin/bash


charset=`file -i $1  | cut -d= -f2`

if [ $charset ]; then   
   iconv  -f $charset -t latin1//TRANSLIT $1  | /usr/bin/a2ps  -1 -B -o - | ps2pdf14 -sPAPERSIZE=a4 - $2
else
   /usr/bin/a2ps -1 -B $1 -o - | ps2pdf14 -sPAPERSIZE=a4 - $2
fi