/* src/config.h.  Generated by configure.  */

/* #undef inline */
/* #undef const */


#define USE_POSTGRES 1



#define PROGNAME "pam_what_access"
#define MAJOR_VERSION 0
#define MINOR_VERSION 3
#define PATCHLEVEL "3"
#define COPYRIGHT_NOTICE "Copyright (c) 2001 Mike Glover"
