# ============================================
# $Id: Makefile,v 1.1 2007/09/07 10:06:14 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+= changelog changelog.in compat control copyright dirs postinst rules
