# ============================================
# $Id: Makefile,v 1.2 2007/07/06 12:20:48 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog compat control copyright dirs postinst rules freedom-vault.logrotate
