# ============================================
# $Id: Makefile,v 1.1 2005/05/24 16:21:52 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule



