#!/bin/bash

pubdir="/home/httpd/what";

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
    echo
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then

  $pubdir/wsh.php --api=freedom_import --file=$pubdir/WGCAL/wgcal.csv
  

fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
