#!/bin/bash

pubdir="/home/httpd/what";
dbfree="freedom";
dbname="anakeen"

if [ "$dbanakeen" = "" ]; then
    dbname="anakeen"
else
    dbname=$dbanakeen
fi
dbfree=`$pubdir/wsh.php --api=get_param --param=FREEDOM_DB | sed -e 's/^.*dbname[[:space:]]*=[[:space:]]*\([[:alnum:]]*\).*$/\1/'`
echo $dbname $dbfree
#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then

  $pubdir/wsh.php  --app=USERCARD --action=USERCARD_INIT 
  $pubdir/wsh.php   --app=USERCARD --action=USERCARD_INIT 
  su - postgres -c "psql $dbfree anakeen -f $pubdir/USERCARD/init.sql"
  su - postgres -c "psql $dbfree anakeen -f $pubdir/API/freedom_clean.sql"
  $pubdir/wsh.php   --api=usercard_iuser
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then

  $pubdir/wsh.php  -a $dbname --app=USERCARD --action=USERCARD_INIT 
  $pubdir/wsh.php  -a $dbname --api=usercard_iuser

fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
