#
# Mike Glover
# mpg4@duluoz.net
#
# Makefile for pam_sql
#
#


#
# BEGIN setting variables
#


# local configuration options
include ./config.mk


# programs to use
SHELL      :=   /bin/sh

CC         :=   gcc
CFLAGS     :=   -g -O -DUSE_POSTGRES -DHAVE_INLINE
CPPFLAGS    =   $(inc)

DIFF       :=   diff
DIFFFLAGS  :=   -uri

INSTALL    :=   install
INSTALL_DATA    :=   $(INSTALL)
INSTALL_PROGRAM :=   $(INSTALL)



# these get built by the included dir.mk's
dirs       :=   .
srcs       := 
libs       :=
inc        :=
objs        =   $(srcs:.c=.o)


# keep track of our current location
dir        :=   $(srcdir)


# look for a dir.mk in these subdirectories
subdirs    :=   src


#
# END   setting variables
# BEGIN including subfiles
#


# include the fragment from each directory
-include $(foreach sdir,$(subdirs),$(dir)/$(sdir)/dir.mk)


#
# END including subfiles
# BEGIN rules
#

# clear out the suffix list and rewrite
.SUFFIXES:
.SUFFIXES: .c .o
.PHONY: all clean distclean dist install uninstall


# compile the program (and the objects)
all: $(prog)
$(prog): $(objs) 


install: $(prog)
	$(NORMAL_INSTALL)
	$(INSTALL_PROGRAM) $(srcdir)/$(prog) $(libdir)/security/$(prog)


uninstall:
	$(NORMAL_UNINSTALL)
	rm -f $(libdir)/security/$(prog)


distdir    :=   $(package)-$(version)
dist: distclean

	mkdir ./$(distdir)
	cp -R $(srcdir)/* ./$(distdir)
	rm -rf ./$(distdir)/$(distdir)
	tar -zcvf $(distdir).tar.gz $(distdir)
	rm -rf ./$(distdir)


cfixes     :=   ~ .o 
clean:
	rm -f $(foreach sfix,$(cfixes),$(addsuffix /*$(sfix),$(dirs)))
	rm -f $(prog) core


dcfixes    :=   .d   
distclean: clean
	rm -f $(foreach sfix,$(dcfixes),$(addsuffix /*$(sfix),$(dirs)))
	rm -rf ./$(distdir)
	rm -rf ./$(distdir).tar.gz



# include object dependencies
-include $(objs:.o=.d)


#
# END   rules
# BEGIN pattern rules
#


# create dependencies automatically from .c files
%.d: %.c
	$(srcdir)/depend.sh $(CPPFLAGS) $< > $@


# create shared library from a collection of object
%.so: 
	$(CC) -shared -Xlinker -x -o $@ $^ $(libs)

