# ============================================
# $Id: Makefile,v 1.2 2007/07/06 12:09:11 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog compat control copyright rules freedom.dirs freedom-lib.dirs freedom-usercard.dirs freedom.postinst freedom-usercard.postinst freedom-lib.postinst
