# ============================================
# $Id: Makefile,v 1.6 2005/10/27 14:43:44 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Usercard  Generic Fusers


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
