# ============================================
# $Id: Makefile,v 1.3 2002/02/13 14:31:59 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Freedom Fdl Usercard Incident


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
