/* src/config.h.  Generated by configure.  */

/* #undef inline */
/* #undef const */


#define USE_POSTGRES 1



#define PROGNAME "pam_what"
#define MAJOR_VERSION 0
#define MINOR_VERSION 4
#define PATCHLEVEL "0"
#define COPYRIGHT_NOTICE "Copyright (c) 2001 Mike Glover"
